<form action="listarS" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Numero Siniestros:</label>
                <input required name="id_Stro" type="text" class="form-control">
               <!-- <label>Apellido:</label>
                <input required name="apellido" type="text" class="form-control">
                <label>Contacto:</label>
                <input required name="contacto" type="text" class="form-control">
                <label>Email:</label>
                <input required name="email" type = "email" class="form-control">
-->         </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>




