<?php require 'templates/header.phtml' ?>
            <tr>
                <td><?= $itemStro->id_Stro ?></td>
                <td><?= $itemStro->tipo_Stro ?></td>
                <td><?= $itemStro->fecha_Stro?></td>
                <td><?= $itemStro->nombre_Asegurado?></td>
                <td><?= $itemStro->apellido_Asegurado?></td>
                <td><?= $itemStro->direccion_Aseg?></td>
                <td><?= $itemStro->contacto_Asegurado?></td>
            </tr>