<?php require 'templates/header.phtml' ?>

<!--<?php require 'templates/form_alta.phtml' ?>-->

<ul class="list-group">
<?php foreach($tasks as $task): ?>
    <li class="list-group-item item-task 
        <div>
        <?php $task->tipo_Stro ?>
            <b><?= $task->tipo_Stro ?></b> | <?=substr($task->tipo_Stro,0,25)?> | (Prioridad <?= $task->tipo_Stro ?>)
        </div>
        <div class="actions">
            <?php if(!$task->finalizada): ?> 
                <a href="finalizar/<?= $task->id ?>" type="button" class='btn btn-success ml-auto'>Finalizar</a> 
            <?php endif ?>
            <a href="eliminar/<?= $task->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> Siniestros</small></p>


<?php require 'templates/footer.phtml' ?>
